language: bonde_js

node_js:
  - "10.14.2"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: "projeto10062020"
  app:
    master: projeto10062020testes
    production: projeto10062020
