language: bonde_js

node_js:
  - "10.14.2"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: "322b8076-825f-409e-9702-d12e30c7f800"
  app:
    master: projeto10062020testes
    production: projeto10062020
