language: bonde_js

node_js:
  - "10.14.2"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: "4ad1593b-0387-4a12-a5d6-02fcedc90539"
  app:
    master: projeto10062020testes
    production: projeto10062020
